### ISSUE TITLE
SyntaxError message in console

### ISSUE THREAD

**Issue by eduenez33** [bldg14/eventual#46]
### Issue Description

When loading the client at [https://eventual-client.fly.dev/](https://eventual-client.fly.dev/), we should be able to see an array of items in the console. Instead we are met with an error message.

`SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON`

[This file is where the bug is occurring](https://github.com/bldg14/eventual/blob/main/src/http/get.ts)

### Implementation Details

TBD

### Acceptance Criteria

Array of items should be visible in the console and the error should go away.

**Comment by kevinfalting** [comment]
It turns out that the dockerfile I wrote doesn't use the build arg appropriately. According to [the docs](https://docs.docker.com/engine/reference/builder/#scope):

> An `ARG` instruction goes out of scope at the end of the build stage where it was defined.

And the backend url build arg in `Dockerfile.client` is defined before the first build stage even begins. Moving this line inside of the first build stage will solve this problem. 

There's actually an additional problem that needs to be looked into, and that is the dockerfile is failing to build locally, specifically at the `npm run build` step.

**Comment by kevinfalting** [comment]
This bug was introduced in https://github.com/bldg14/eventual/pull/44

**Comment by kevinfalting** [comment]
> There's actually an additional problem that needs to be looked into, and that is the dockerfile is failing to build locally, specifically at the `npm run build` step.

I've tried building it on another computer and the fly.io builder, it worked fine. There must be something off about my personal computer. This doesn't seem to be a bug with the project.
